
 Date: 1403/10/28 | Message: One or more errors occurred. (Value cannot be null. (Parameter 'source')) | Source: System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'source'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Domic.Core.Domain.Extensions.StringExtension.HashAsync(String Input, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Domic.UseCase.UserUseCase.Events.UpdateUserConsumerEventBusHandler.HandleAsync(UserUpdated event, CancellationToken cancellationToken) in D:\Programming\Domic\Domic-UserService\src\Core\Domic.UseCase\UserUseCase\Events\UpdateUserConsumerEventBusHandler.cs:line 55
   at Domic.Core.Infrastructure.Concretes.ExternalMessageBroker._EventOfQueueHandleAsync(IModel channel, BasicDeliverEventArgs args, Event event, IServiceProvider serviceProvider, CancellationToken cancellationToken) 


 Date: 1403/10/28 | Message: One or more errors occurred. (Value cannot be null. (Parameter 'source')) | Source: System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'source'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Domic.Core.Domain.Extensions.StringExtension.HashAsync(String Input, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Domic.UseCase.UserUseCase.Events.UpdateUserConsumerEventBusHandler.HandleAsync(UserUpdated event, CancellationToken cancellationToken) in D:\Programming\Domic\Domic-UserService\src\Core\Domic.UseCase\UserUseCase\Events\UpdateUserConsumerEventBusHandler.cs:line 55
   at Domic.Core.Infrastructure.Concretes.ExternalMessageBroker._EventOfQueueHandleAsync(IModel channel, BasicDeliverEventArgs args, Event event, IServiceProvider serviceProvider, CancellationToken cancellationToken) 


 Date: 1403/10/28 | Message: One or more errors occurred. (Value cannot be null. (Parameter 'source')) | Source: System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'source'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Domic.Core.Domain.Extensions.StringExtension.HashAsync(String Input, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Domic.UseCase.UserUseCase.Events.UpdateUserConsumerEventBusHandler.HandleAsync(UserUpdated event, CancellationToken cancellationToken) in D:\Programming\Domic\Domic-UserService\src\Core\Domic.UseCase\UserUseCase\Events\UpdateUserConsumerEventBusHandler.cs:line 55
   at Domic.Core.Infrastructure.Concretes.ExternalMessageBroker._EventOfQueueHandleAsync(IModel channel, BasicDeliverEventArgs args, Event event, IServiceProvider serviceProvider, CancellationToken cancellationToken) 


 Date: 1403/10/28 | Message: One or more errors occurred. (Value cannot be null. (Parameter 'source')) | Source: System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'source'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Domic.Core.Domain.Extensions.StringExtension.HashAsync(String Input, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Domic.UseCase.UserUseCase.Events.UpdateUserConsumerEventBusHandler.HandleAsync(UserUpdated event, CancellationToken cancellationToken) in D:\Programming\Domic\Domic-UserService\src\Core\Domic.UseCase\UserUseCase\Events\UpdateUserConsumerEventBusHandler.cs:line 55
   at Domic.Core.Infrastructure.Concretes.ExternalMessageBroker._EventOfQueueHandleAsync(IModel channel, BasicDeliverEventArgs args, Event event, IServiceProvider serviceProvider, CancellationToken cancellationToken) 


 Date: 1403/10/28 | Message: One or more errors occurred. (Value cannot be null. (Parameter 'source')) | Source: System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'source'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Domic.Core.Domain.Extensions.StringExtension.HashAsync(String Input, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Domic.UseCase.UserUseCase.Events.UpdateUserConsumerEventBusHandler.HandleAsync(UserUpdated event, CancellationToken cancellationToken) in D:\Programming\Domic\Domic-UserService\src\Core\Domic.UseCase\UserUseCase\Events\UpdateUserConsumerEventBusHandler.cs:line 55
   at Domic.Core.Infrastructure.Concretes.ExternalMessageBroker._EventOfQueueHandleAsync(IModel channel, BasicDeliverEventArgs args, Event event, IServiceProvider serviceProvider, CancellationToken cancellationToken) 


 Date: 1403/10/28 | Message: One or more errors occurred. (Value cannot be null. (Parameter 'source')) | Source: System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'source'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Domic.Core.Domain.Extensions.StringExtension.HashAsync(String Input, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Domic.UseCase.UserUseCase.Events.UpdateUserConsumerEventBusHandler.HandleAsync(UserUpdated event, CancellationToken cancellationToken) in D:\Programming\Domic\Domic-UserService\src\Core\Domic.UseCase\UserUseCase\Events\UpdateUserConsumerEventBusHandler.cs:line 55
   at Domic.Core.Infrastructure.Concretes.ExternalMessageBroker._EventOfQueueHandleAsync(IModel channel, BasicDeliverEventArgs args, Event event, IServiceProvider serviceProvider, CancellationToken cancellationToken) 


 Date: 1403/10/28 | Message: One or more errors occurred. (Value cannot be null. (Parameter 'source')) | Source: System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'source'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Domic.Core.Domain.Extensions.StringExtension.HashAsync(String Input, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Domic.UseCase.UserUseCase.Events.UpdateUserConsumerEventBusHandler.HandleAsync(UserUpdated event, CancellationToken cancellationToken) in D:\Programming\Domic\Domic-UserService\src\Core\Domic.UseCase\UserUseCase\Events\UpdateUserConsumerEventBusHandler.cs:line 55
   at Domic.Core.Infrastructure.Concretes.ExternalMessageBroker._EventOfQueueHandleAsync(IModel channel, BasicDeliverEventArgs args, Event event, IServiceProvider serviceProvider, CancellationToken cancellationToken) 


 Date: 1403/10/28 | Message: One or more errors occurred. (Value cannot be null. (Parameter 'source')) | Source: System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'source'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Domic.Core.Domain.Extensions.StringExtension.HashAsync(String Input, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Domic.UseCase.UserUseCase.Events.UpdateUserConsumerEventBusHandler.HandleAsync(UserUpdated event, CancellationToken cancellationToken) in D:\Programming\Domic\Domic-UserService\src\Core\Domic.UseCase\UserUseCase\Events\UpdateUserConsumerEventBusHandler.cs:line 55
   at Domic.Core.Infrastructure.Concretes.ExternalMessageBroker._EventOfQueueHandleAsync(IModel channel, BasicDeliverEventArgs args, Event event, IServiceProvider serviceProvider, CancellationToken cancellationToken) 


 Date: 1403/10/28 | Message: One or more errors occurred. (Value cannot be null. (Parameter 'source')) | Source: System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'source'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Domic.Core.Domain.Extensions.StringExtension.HashAsync(String Input, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Domic.UseCase.UserUseCase.Events.UpdateUserConsumerEventBusHandler.HandleAsync(UserUpdated event, CancellationToken cancellationToken) in D:\Programming\Domic\Domic-UserService\src\Core\Domic.UseCase\UserUseCase\Events\UpdateUserConsumerEventBusHandler.cs:line 55
   at Domic.Core.Infrastructure.Concretes.ExternalMessageBroker._EventOfQueueHandleAsync(IModel channel, BasicDeliverEventArgs args, Event event, IServiceProvider serviceProvider, CancellationToken cancellationToken) 


 Date: 1403/10/28 | Message: One or more errors occurred. (Value cannot be null. (Parameter 'source')) | Source: System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'source'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Domic.Core.Domain.Extensions.StringExtension.HashAsync(String Input, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Domic.UseCase.UserUseCase.Events.UpdateUserConsumerEventBusHandler.HandleAsync(UserUpdated event, CancellationToken cancellationToken) in D:\Programming\Domic\Domic-UserService\src\Core\Domic.UseCase\UserUseCase\Events\UpdateUserConsumerEventBusHandler.cs:line 55
   at Domic.Core.Infrastructure.Concretes.ExternalMessageBroker._EventOfQueueHandleAsync(IModel channel, BasicDeliverEventArgs args, Event event, IServiceProvider serviceProvider, CancellationToken cancellationToken) 


 Date: 1403/10/28 | Message: One or more errors occurred. (Value cannot be null. (Parameter 'source')) | Source: System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'source'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Domic.Core.Domain.Extensions.StringExtension.HashAsync(String Input, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Domic.UseCase.UserUseCase.Events.UpdateUserConsumerEventBusHandler.HandleAsync(UserUpdated event, CancellationToken cancellationToken) in D:\Programming\Domic\Domic-UserService\src\Core\Domic.UseCase\UserUseCase\Events\UpdateUserConsumerEventBusHandler.cs:line 55
   at Domic.Core.Infrastructure.Concretes.ExternalMessageBroker._EventOfQueueHandleAsync(IModel channel, BasicDeliverEventArgs args, Event event, IServiceProvider serviceProvider, CancellationToken cancellationToken) 


 Date: 1403/10/28 | Message: One or more errors occurred. (Value cannot be null. (Parameter 'source')) | Source: System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'source'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Domic.Core.Domain.Extensions.StringExtension.HashAsync(String Input, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Domic.UseCase.UserUseCase.Events.UpdateUserConsumerEventBusHandler.HandleAsync(UserUpdated event, CancellationToken cancellationToken) in D:\Programming\Domic\Domic-UserService\src\Core\Domic.UseCase\UserUseCase\Events\UpdateUserConsumerEventBusHandler.cs:line 55
   at Domic.Core.Infrastructure.Concretes.ExternalMessageBroker._EventOfQueueHandleAsync(IModel channel, BasicDeliverEventArgs args, Event event, IServiceProvider serviceProvider, CancellationToken cancellationToken) 


 Date: 1403/10/28 | Message: One or more errors occurred. (Value cannot be null. (Parameter 'source')) | Source: System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'source'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Domic.Core.Domain.Extensions.StringExtension.HashAsync(String Input, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Domic.UseCase.UserUseCase.Events.UpdateUserConsumerEventBusHandler.HandleAsync(UserUpdated event, CancellationToken cancellationToken) in D:\Programming\Domic\Domic-UserService\src\Core\Domic.UseCase\UserUseCase\Events\UpdateUserConsumerEventBusHandler.cs:line 55
   at Domic.Core.Infrastructure.Concretes.ExternalMessageBroker._EventOfQueueHandleAsync(IModel channel, BasicDeliverEventArgs args, Event event, IServiceProvider serviceProvider, CancellationToken cancellationToken) 


 Date: 1403/10/28 | Message: One or more errors occurred. (Value cannot be null. (Parameter 'source')) | Source: System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'source'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Domic.Core.Domain.Extensions.StringExtension.HashAsync(String Input, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Domic.UseCase.UserUseCase.Events.UpdateUserConsumerEventBusHandler.HandleAsync(UserUpdated event, CancellationToken cancellationToken) in D:\Programming\Domic\Domic-UserService\src\Core\Domic.UseCase\UserUseCase\Events\UpdateUserConsumerEventBusHandler.cs:line 55
   at Domic.Core.Infrastructure.Concretes.ExternalMessageBroker._EventOfQueueHandleAsync(IModel channel, BasicDeliverEventArgs args, Event event, IServiceProvider serviceProvider, CancellationToken cancellationToken) 


 Date: 1403/10/28 | Message: One or more errors occurred. (Value cannot be null. (Parameter 'source')) | Source: System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'source'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Domic.Core.Domain.Extensions.StringExtension.HashAsync(String Input, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Domic.UseCase.UserUseCase.Events.UpdateUserConsumerEventBusHandler.HandleAsync(UserUpdated event, CancellationToken cancellationToken) in D:\Programming\Domic\Domic-UserService\src\Core\Domic.UseCase\UserUseCase\Events\UpdateUserConsumerEventBusHandler.cs:line 55
   at Domic.Core.Infrastructure.Concretes.ExternalMessageBroker._EventOfQueueHandleAsync(IModel channel, BasicDeliverEventArgs args, Event event, IServiceProvider serviceProvider, CancellationToken cancellationToken) 


 Date: 1403/10/28 | Message: One or more errors occurred. (Value cannot be null. (Parameter 'source')) | Source: System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'source'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Domic.Core.Domain.Extensions.StringExtension.HashAsync(String Input, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Domic.UseCase.UserUseCase.Events.UpdateUserConsumerEventBusHandler.HandleAsync(UserUpdated event, CancellationToken cancellationToken) in D:\Programming\Domic\Domic-UserService\src\Core\Domic.UseCase\UserUseCase\Events\UpdateUserConsumerEventBusHandler.cs:line 55
   at Domic.Core.Infrastructure.Concretes.ExternalMessageBroker._EventOfQueueHandleAsync(IModel channel, BasicDeliverEventArgs args, Event event, IServiceProvider serviceProvider, CancellationToken cancellationToken) 


 Date: 1403/10/28 | Message: One or more errors occurred. (Value cannot be null. (Parameter 'source')) | Source: System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'source'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Domic.Core.Domain.Extensions.StringExtension.HashAsync(String Input, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Domic.UseCase.UserUseCase.Events.UpdateUserConsumerEventBusHandler.HandleAsync(UserUpdated event, CancellationToken cancellationToken) in D:\Programming\Domic\Domic-UserService\src\Core\Domic.UseCase\UserUseCase\Events\UpdateUserConsumerEventBusHandler.cs:line 55
   at Domic.Core.Infrastructure.Concretes.ExternalMessageBroker._EventOfQueueHandleAsync(IModel channel, BasicDeliverEventArgs args, Event event, IServiceProvider serviceProvider, CancellationToken cancellationToken) 


 Date: 1403/10/28 | Message: One or more errors occurred. (Value cannot be null. (Parameter 'source')) | Source: System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'source'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Domic.Core.Domain.Extensions.StringExtension.HashAsync(String Input, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Domic.UseCase.UserUseCase.Events.UpdateUserConsumerEventBusHandler.HandleAsync(UserUpdated event, CancellationToken cancellationToken) in D:\Programming\Domic\Domic-UserService\src\Core\Domic.UseCase\UserUseCase\Events\UpdateUserConsumerEventBusHandler.cs:line 55
   at Domic.Core.Infrastructure.Concretes.ExternalMessageBroker._EventOfQueueHandleAsync(IModel channel, BasicDeliverEventArgs args, Event event, IServiceProvider serviceProvider, CancellationToken cancellationToken) 


 Date: 1403/10/28 | Message: One or more errors occurred. (Value cannot be null. (Parameter 'source')) | Source: System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'source'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Domic.Core.Domain.Extensions.StringExtension.HashAsync(String Input, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Domic.UseCase.UserUseCase.Events.UpdateUserConsumerEventBusHandler.HandleAsync(UserUpdated event, CancellationToken cancellationToken) in D:\Programming\Domic\Domic-UserService\src\Core\Domic.UseCase\UserUseCase\Events\UpdateUserConsumerEventBusHandler.cs:line 55
   at Domic.Core.Infrastructure.Concretes.ExternalMessageBroker._EventOfQueueHandleAsync(IModel channel, BasicDeliverEventArgs args, Event event, IServiceProvider serviceProvider, CancellationToken cancellationToken) 


 Date: 1403/10/28 | Message: One or more errors occurred. (Value cannot be null. (Parameter 'source')) | Source: System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'source'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Domic.Core.Domain.Extensions.StringExtension.HashAsync(String Input, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Domic.UseCase.UserUseCase.Events.UpdateUserConsumerEventBusHandler.HandleAsync(UserUpdated event, CancellationToken cancellationToken) in D:\Programming\Domic\Domic-UserService\src\Core\Domic.UseCase\UserUseCase\Events\UpdateUserConsumerEventBusHandler.cs:line 55
   at Domic.Core.Infrastructure.Concretes.ExternalMessageBroker._EventOfQueueHandleAsync(IModel channel, BasicDeliverEventArgs args, Event event, IServiceProvider serviceProvider, CancellationToken cancellationToken) 


 Date: 1403/10/28 | Message: One or more errors occurred. (Value cannot be null. (Parameter 'source')) | Source: System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'source'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Domic.Core.Domain.Extensions.StringExtension.HashAsync(String Input, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Domic.UseCase.UserUseCase.Events.UpdateUserConsumerEventBusHandler.HandleAsync(UserUpdated event, CancellationToken cancellationToken) in D:\Programming\Domic\Domic-UserService\src\Core\Domic.UseCase\UserUseCase\Events\UpdateUserConsumerEventBusHandler.cs:line 55
   at Domic.Core.Infrastructure.Concretes.ExternalMessageBroker._EventOfQueueHandleAsync(IModel channel, BasicDeliverEventArgs args, Event event, IServiceProvider serviceProvider, CancellationToken cancellationToken) 


 Date: 1403/10/28 | Message: One or more errors occurred. (Value cannot be null. (Parameter 'source')) | Source: System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'source'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Domic.Core.Domain.Extensions.StringExtension.HashAsync(String Input, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Domic.UseCase.UserUseCase.Events.UpdateUserConsumerEventBusHandler.HandleAsync(UserUpdated event, CancellationToken cancellationToken) in D:\Programming\Domic\Domic-UserService\src\Core\Domic.UseCase\UserUseCase\Events\UpdateUserConsumerEventBusHandler.cs:line 55
   at Domic.Core.Infrastructure.Concretes.ExternalMessageBroker._EventOfQueueHandleAsync(IModel channel, BasicDeliverEventArgs args, Event event, IServiceProvider serviceProvider, CancellationToken cancellationToken) 


 Date: 1403/10/28 | Message: One or more errors occurred. (Value cannot be null. (Parameter 'source')) | Source: System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'source'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Domic.Core.Domain.Extensions.StringExtension.HashAsync(String Input, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Domic.UseCase.UserUseCase.Events.UpdateUserConsumerEventBusHandler.HandleAsync(UserUpdated event, CancellationToken cancellationToken) in D:\Programming\Domic\Domic-UserService\src\Core\Domic.UseCase\UserUseCase\Events\UpdateUserConsumerEventBusHandler.cs:line 55
   at Domic.Core.Infrastructure.Concretes.ExternalMessageBroker._EventOfQueueHandleAsync(IModel channel, BasicDeliverEventArgs args, Event event, IServiceProvider serviceProvider, CancellationToken cancellationToken) 


 Date: 1403/10/28 | Message: One or more errors occurred. (Value cannot be null. (Parameter 'source')) | Source: System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'source'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Domic.Core.Domain.Extensions.StringExtension.HashAsync(String Input, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Domic.UseCase.UserUseCase.Events.UpdateUserConsumerEventBusHandler.HandleAsync(UserUpdated event, CancellationToken cancellationToken) in D:\Programming\Domic\Domic-UserService\src\Core\Domic.UseCase\UserUseCase\Events\UpdateUserConsumerEventBusHandler.cs:line 55
   at Domic.Core.Infrastructure.Concretes.ExternalMessageBroker._EventOfQueueHandleAsync(IModel channel, BasicDeliverEventArgs args, Event event, IServiceProvider serviceProvider, CancellationToken cancellationToken) 


 Date: 1403/10/28 | Message: One or more errors occurred. (Value cannot be null. (Parameter 'source')) | Source: System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'source'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Domic.Core.Domain.Extensions.StringExtension.HashAsync(String Input, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Domic.UseCase.UserUseCase.Events.UpdateUserConsumerEventBusHandler.HandleAsync(UserUpdated event, CancellationToken cancellationToken) in D:\Programming\Domic\Domic-UserService\src\Core\Domic.UseCase\UserUseCase\Events\UpdateUserConsumerEventBusHandler.cs:line 55
   at Domic.Core.Infrastructure.Concretes.ExternalMessageBroker._EventOfQueueHandleAsync(IModel channel, BasicDeliverEventArgs args, Event event, IServiceProvider serviceProvider, CancellationToken cancellationToken) 


 Date: 1403/10/28 | Message: One or more errors occurred. (Value cannot be null. (Parameter 'source')) | Source: System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'source'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Domic.Core.Domain.Extensions.StringExtension.HashAsync(String Input, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Domic.UseCase.UserUseCase.Events.UpdateUserConsumerEventBusHandler.HandleAsync(UserUpdated event, CancellationToken cancellationToken) in D:\Programming\Domic\Domic-UserService\src\Core\Domic.UseCase\UserUseCase\Events\UpdateUserConsumerEventBusHandler.cs:line 55
   at Domic.Core.Infrastructure.Concretes.ExternalMessageBroker._EventOfQueueHandleAsync(IModel channel, BasicDeliverEventArgs args, Event event, IServiceProvider serviceProvider, CancellationToken cancellationToken) 


 Date: 1403/10/28 | Message: One or more errors occurred. (Value cannot be null. (Parameter 'source')) | Source: System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'source'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Domic.Core.Domain.Extensions.StringExtension.HashAsync(String Input, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Domic.UseCase.UserUseCase.Events.UpdateUserConsumerEventBusHandler.HandleAsync(UserUpdated event, CancellationToken cancellationToken) in D:\Programming\Domic\Domic-UserService\src\Core\Domic.UseCase\UserUseCase\Events\UpdateUserConsumerEventBusHandler.cs:line 55
   at Domic.Core.Infrastructure.Concretes.ExternalMessageBroker._EventOfQueueHandleAsync(IModel channel, BasicDeliverEventArgs args, Event event, IServiceProvider serviceProvider, CancellationToken cancellationToken) 


 Date: 1403/10/28 | Message: One or more errors occurred. (Value cannot be null. (Parameter 'source')) | Source: System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'source'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Domic.Core.Domain.Extensions.StringExtension.HashAsync(String Input, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Domic.UseCase.UserUseCase.Events.UpdateUserConsumerEventBusHandler.HandleAsync(UserUpdated event, CancellationToken cancellationToken) in D:\Programming\Domic\Domic-UserService\src\Core\Domic.UseCase\UserUseCase\Events\UpdateUserConsumerEventBusHandler.cs:line 55
   at Domic.Core.Infrastructure.Concretes.ExternalMessageBroker._EventOfQueueHandleAsync(IModel channel, BasicDeliverEventArgs args, Event event, IServiceProvider serviceProvider, CancellationToken cancellationToken) 

